//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Виды_жилья
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Виды_жилья()
        {
            this.Путевки = new HashSet<Путевки>();
        }
    
        public int ID_Вид_жилья { get; set; }
        public string Название { get; set; }
        public int ID_Пансионата { get; set; }
        public string Категория_жилья { get; set; }
        public string Описание_условий_проживаний { get; set; }
        public decimal Цена_за_номер_в_сутки { get; set; }
    
        public virtual Пансионаты Пансионаты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Путевки> Путевки { get; set; }
    }
}
