//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Путевки
    {
        public int ID_Путевки { get; set; }
        public int ID_Клиента { get; set; }
        public Nullable<int> ID_Пансионата { get; set; }
        public Nullable<int> ID_Вид_жилья { get; set; }
        public Nullable<int> ID_Тура { get; set; }
        public System.DateTime Дата_заезда { get; set; }
        public System.DateTime Дата_отъезда { get; set; }
        public bool Наличие_детей { get; set; }
        public bool Наличие_мед__страховки { get; set; }
        public int Количество_человек { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<decimal> Итоговая_цена { get; set; }


        public string FIO
        {
            get
            {
                return Клиенты.Фамилия + " " + Клиенты.Имя + " " + Клиенты.Отчество;
            }
        }

        public string КлиентString
        {
            get
            {
                if (Клиенты.ID_Клиента == ID_Клиента)
                {
                    return Клиенты.Фамилия + " " + Клиенты.Имя + " " + Клиенты.Отчество;
                }
                return "";
            }
        }

        public string Наличие_детейstring
        {
            get
            {
                if (Наличие_детей == true)
                {
                    return "Есть";
                }
                else
                    return "Нету";
            }
        }

        public string Наличие_мед_страховкиstring
        {
            get
            {
                if (Наличие_мед__страховки == true)
                {
                    return "Есть";
                }
                else
                    return "Нету";
            }
        }

        public virtual Виды_жилья Виды_жилья { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Пансионаты Пансионаты { get; set; }
        public virtual Туры Туры { get; set; }
    }
}
