//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Туры_для_триггера
    {
        public int ID_Тура { get; set; }
        public string Название { get; set; }
        public string Вид_транспорта { get; set; }
        public string Категория_жилья_на_ночь { get; set; }
        public string Вид_питания { get; set; }
        public decimal Цена_тура_в_сутки { get; set; }
    }
}
